@BASE_URL = http://localhost:3000
//@userId = 691af6ce679594af902955ed
@userId = 694769a0b3c4a0fb949d7263
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTQ3N2QyNmY0MDE3YTY4NDNiMTk4Y2IiLCJpYXQiOjE3NjYzNzQ3MTMsImV4cCI6MTc2NjQ2MTExM30.qJv1VjN7ctf1FKC47CY8wsmjjOrY8Ot-jJwtC49OyuM

### Create a new user
POST {{BASE_URL}}/users
Content-Type: application/json

{
    "name": "Rupesh Rajbanshi",
    "email": "rupesh.raj@example.com",
    "password": "password"
}

### Get all users
GET {{BASE_URL}}/users

### Get user by id
GET {{BASE_URL}}/users/69477d26f4017a6843b198cb

### Update user by id
PATCH {{BASE_URL}}/users/69477d26f4017a6843b198cb

Content-Type: application/json

{
    "email": "rupesh.rajbanshi@example.com"
}

### Delete user by id
DELETE {{BASE_URL}}/users/694769a0b3c4a0fb949d7263

### Register a new user
POST {{BASE_URL}}/auth/register
Content-Type: application/json

{
  "name": "Rupesh Rajbanshi",
  "email": "rajbanshi@example.com",
  "password": "password"
}

### Login a user
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
  "email": "rajbanshi@example.com",
  "password": "password"
}

###Create a new trip
POST {{BASE_URL}}/trips
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Trip to the moon",
  "startDate": "2025-12-15",
  "endDate": "2025-12-16",
  "budget": {
    "total": 1000
  },
  "destinations": ["Moon", "Mars", "Jupiter"]
}
